name: qcsp
description: Generate CSP compliant hash sources with a few keystrokes.
version: 0.1.0
repository: https://github.com/jqpe/qcsp

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.4.2
  cryptography: ^2.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executable: qcsp
