name: Release

defaults:
  run:
    shell: bash

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build:
    permissions:
      contents: write
    needs: ci
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output-name: qcsp-linux
          - os: macOS-latest
            output-name: qcsp-macos
          - os: windows-latest
            output-name: qcsp.exe

    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.1
      - run: dart pub get
      - run: mkdir build
      - run: dart compile exe ./bin/qcsp.dart -v -o ./build/${{ matrix.output-name }}

      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./build/${{ matrix.output-name }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.output-name }}
          overwrite: true
